/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [Retailer]
      ,[Retailer ID]
      ,[Invoice Date]
      ,[Region]
      ,[State]
      ,[City]
      ,[Product]
      ,[Price per Unit]
      ,[Units Sold]
      ,[Total Sales]
      ,[Operating Profit]
      ,[Operating Margin]
      ,[Sales Method]
  FROM [Addidas Sales].[dbo].['Data Sales Adidas$']